### ISSUE TITLE
IOS UI Issues - Alignment and Text Display Issues

### ISSUE THREAD

**Issue by shankarag** [HelpinOutMovement/helpinout-app-reactnative#11]
![IMG_1808](https://user-images.githubusercontent.com/18084588/79943388-6862a200-8486-11ea-8fb3-b89537244466.PNG)
![IMG_1807](https://user-images.githubusercontent.com/18084588/79943391-6a2c6580-8486-11ea-8463-871025753735.PNG)
![IMG_1806](https://user-images.githubusercontent.com/18084588/79943393-6ac4fc00-8486-11ea-9cae-898b43455a55.PNG)
![IMG_1815](https://user-images.githubusercontent.com/18084588/79943397-6bf62900-8486-11ea-8abd-3bc74c1f8984.PNG)
![IMG_1814](https://user-images.githubusercontent.com/18084588/79943399-6bf62900-8486-11ea-81e8-c53f5c48d6d6.PNG)
![IMG_1813](https://user-images.githubusercontent.com/18084588/79943400-6c8ebf80-8486-11ea-8372-4816eebce262.PNG)
![IMG_1812](https://user-images.githubusercontent.com/18084588/79943402-6d275600-8486-11ea-86b1-d0aadb262100.PNG)
![IMG_1811](https://user-images.githubusercontent.com/18084588/79943405-6d275600-8486-11ea-8a63-4007a5ab8288.PNG)
![IMG_1810](https://user-images.githubusercontent.com/18084588/79943406-6dbfec80-8486-11ea-9456-7029d2cf7640.PNG)
![IMG_1809](https://user-images.githubusercontent.com/18084588/79943407-6e588300-8486-11ea-919a-bb3f4922d20b.PNG)

[

**Comment by shankarag** [comment]
Iphone XR - IOS - 13.4.1

**Comment by vsrvraghavan** [comment]
Fixed in build 1.0.37
