### ISSUE TITLE
Shankar A:  The flow of sending request is bit confusing. It asks me to cancel and not do done

### ISSUE THREAD

**Issue by deviator206** [HelpinOutMovement/helpinout-app-reactnative#17]
![image](https://user-images.githubusercontent.com/1659309/80806761-2699d000-8bd9-11ea-8146-9aca876df146.png)

The flow of sending request is bit confusing. It asks me to cancel and not do done

**Comment by vsrvraghavan** [comment]
Fixed with the new UI flow
