### ISSUE TITLE
iphoneXR : UI alignment

### ISSUE THREAD

**Issue by deviator206** [HelpinOutMovement/helpinout-app-reactnative#31]
![image](https://user-images.githubusercontent.com/1659309/81030711-64cc1380-8ea7-11ea-8fb2-a5c829bb38e0.png)

![image](https://user-images.githubusercontent.com/1659309/81030724-70b7d580-8ea7-11ea-9538-36e0519da137.png)

![image](https://user-images.githubusercontent.com/1659309/81030734-7c0b0100-8ea7-11ea-8cba-b4ff5a1bd788.png)

![image](https://user-images.githubusercontent.com/1659309/81030747-8a591d00-8ea7-11ea-9a22-02806948a60b.png)

**Comment by vsrvraghavan** [comment]
Fixed in build 1.0.39
